### PR TITLE
add initial Pixel API 26 configs

### PR DESCRIPTION
**Pull request by thestinger**

### CODE REVIEW

**Comment by thestinger** [comment]
I had to use this temporary hack for now, along with adjusting the download process for the preview images to test this:

```diff
diff --git a/execute-all.sh b/execute-all.sh
index ce1ec61..ee13ca7 100755
--- a/execute-all.sh
+++ b/execute-all.sh
@@ -103,9 +103,9 @@ oatdump_prepare_env() {
 
 
   if [[ "$HOST_OS" == "Darwin" ]]; then
-    download_url="D_OATDUMP_URL_API$api_level"
+    download_url="D_OATDUMP_URL_API25"
   else
-    download_url="L_OATDUMP_URL_API$api_level"
+    download_url="L_OATDUMP_URL_API25"
   fi
 
   wget -O "$out_file" "${!download_url}" || {

```

**Comment by thestinger** [comment]
The current naming of symlink modules is broken now since it uses `toybox_vendor` for each symlink to toybox_vendor in /vendor/bin:

```
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 acpi -> toybox_vendor
-rwxr-xr-x 1 root     2000 6.2K Jan  1  2009 adsprpcd
-rwxr-xr-x 1 root     2000  28K Jan  1  2009 ATFWD-daemon
-rwxr-xr-x 1 root     2000  40K Jan  1  2009 athdiag
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 base64 -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 basename -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 blockdev -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 cal -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 cat -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 chcon -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 chgrp -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 chmod -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 chown -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 chroot -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 chrt -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 cksum -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 clear -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 cmp -> toybox_vendor
-rwxr-xr-x 1 root     2000  15K Jan  1  2009 cnd
-rwxr-xr-x 1 strcat strcat  24K Jan  1  2009 cnss-daemon
-rwxr-xr-x 1 root     2000 287K Jan  1  2009 cnss_diag
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 comm -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 cp -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 cpio -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 cut -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 date -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 df -> toybox_vendor
-rwxr-xr-x 1 root     2000  11K Jan  1  2009 diag_callback_sample
-rwxr-xr-x 1 root     2000  20K Jan  1  2009 diag_dci_sample
-rwxr-xr-x 1 root     2000  28K Jan  1  2009 diag_mdlog
-rwxr-xr-x 1 root     2000  25K Jan  1  2009 diag_socket_log
-rwxr-xr-x 1 root     2000  16K Jan  1  2009 diag_uart_log
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 dirname -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 dmesg -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 dos2unix -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 du -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 echo -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 env -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 expand -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 expr -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 fallocate -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 false -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 file -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 find -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 flock -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 free -> toybox_vendor
-rwxr-xr-x 1 root     2000  65K Jan  1  2009 ftmdaemon
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 getenforce -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 getprop -> toybox_vendor
-rwxr-xr-x 1 root     2000  25K Jan  1  2009 gptest
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 groups -> toybox_vendor
-rwxr-xr-x 1 root     2000 141K Jan  1  2009 hci_qcomm_init
-rwxr-xr-x 1 root     2000  11K Jan  1  2009 hdcp1prov
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 head -> toybox_vendor
-rwxr-xr-x 1   1010   1010 620K Jan  1  2009 hostapd
-rwxr-xr-x 1 root     2000  65K Jan  1  2009 hostapd_cli
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 hostname -> toybox_vendor
drwxr-xr-x 2 root     2000 4.0K Jan  1  2009 hw
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 hwclock -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 id -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 ifconfig -> toybox_vendor
-rwxr-xr-x 1 root     2000 6.2K Jan  1  2009 imscmservice
-rwxr-xr-x 1 strcat strcat 163K Jan  1  2009 imsdatadaemon
-rwxr-xr-x 1 root     2000 111K Jan  1  2009 imsqmidaemon
-rwxr-xr-x 1 strcat   1001 125K Jan  1  2009 ims_rtp_daemon
-rwxr-xr-x 1 root     2000  287 Jan  1  2009 init.foreground.sh
-rwxr-xr-x 1 root     2000  180 Jan  1  2009 init.mid.sh
-rwxr-xr-x 1 root     2000 4.6K Jan  1  2009 init.power.sh
-rwxr-xr-x 1 root     2000  115 Jan  1  2009 init.qcom.devstart.sh
-rwxr-xr-x 1 root     2000 1.2K Jan  1  2009 init.radio.sh
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 inotifyd -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 insmod -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 ionice -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 iorenice -> toybox_vendor
-rwxr-xr-x 1 root     2000  11K Jan  1  2009 irsc_util
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 kill -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 killall -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 ln -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 load_policy -> toybox_vendor
-rwxr-xr-x 1 root     2000  83K Jan  1  2009 loc_launcher
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 log -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 logname -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 losetup -> toybox_vendor
-rwxr-xr-x 1 root     2000 540K Jan  1  2009 lowi-server
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 ls -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 lsmod -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 lsof -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 lsusb -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 md5sum -> toybox_vendor
-rwxr-xr-x 1 root     2000  28K Jan  1  2009 mdm_helper
-rwxr-xr-x 1 root     2000  28K Jan  1  2009 mdm_helper_proxy
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 microcom -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 mkdir -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 mknod -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 mkswap -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 mktemp -> toybox_vendor
-rwx------ 1   1006   2000  29K Jan  1  2009 mm-qcamera-daemon
-rwxr-xr-x 1 root     2000  25K Jan  1  2009 mm-qjpeg-dec-test
-rwxr-xr-x 1 root     2000  25K Jan  1  2009 mm-qjpeg-enc-test
-rwxr-xr-x 1 root     2000  29K Jan  1  2009 mm-qomx-idec-test
-rwxr-xr-x 1 root     2000  37K Jan  1  2009 mm-qomx-ienc-test
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 modinfo -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 modprobe -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 more -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 mount -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 mountpoint -> toybox_vendor
-rwxr-xr-x 1 root     2000  24K Jan  1  2009 msm_irqbalance
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 mv -> toybox_vendor
-rwxr-xr-x 1 root     2000 113K Jan  1  2009 myftm
-rwxr-xr-x 1 root     2000  16K Jan  1  2009 nanoapp_cmd
-rwxr-xr-x 1 root     2000  17K Jan  1  2009 nanohub_slpi
-rwxr-xr-x 1 root     2000 1.9M Jan  1  2009 netmgrd
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 netstat -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 nice -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 nl -> toybox_vendor
-rwxr-xr-x 1 root     2000 6.9K Jan  1  2009 nl_listener
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 nohup -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 od -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 paste -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 patch -> toybox_vendor
-rwxr-xr-x 1 root     2000 125K Jan  1  2009 perfd
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 pgrep -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 pidof -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 pkill -> toybox_vendor
-rwxr-xr-x 1 root     2000  11K Jan  1  2009 PktRspTest
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 pmap -> toybox_vendor
-rwxr-xr-x 1 root     2000 6.9K Jan  1  2009 pm-proxy
-rwxr-xr-x 1 strcat strcat  54K Jan  1  2009 pm-service
-rwxr-xr-x 1 root     2000  28K Jan  1  2009 port-bridge
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 printenv -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 printf -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 ps -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 pwd -> toybox_vendor
-rwxr-xr-x 1 root     2000 6.7K Jan  1  2009 qfipsverify
-rwxr-xr-x 1 root     2000  24K Jan  1  2009 qjpeg-dma-test
-rwxr-xr-x 1 root     2000  12K Jan  1  2009 qseecomd
-rwxr-xr-x 1 root     2000  44K Jan  1  2009 qseecom_sample_client
-rwxr-xr-x 1 root     2000 127K Jan  1  2009 qti
-rwxr-xr-x 1 root     2000  44K Jan  1  2009 radish
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 readlink -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 realpath -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 renice -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 restorecon -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 rm -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 rmdir -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 rmmod -> toybox_vendor
-rwxr-xr-x 1 root     2000  18K Jan  1  2009 rmnetcli
-rwxr-xr-x 1 root     2000  29K Jan  1  2009 rmt_storage
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 runcon -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sed -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sendevent -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 seq -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 setenforce -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 setprop -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 setsid -> toybox_vendor
-rwxr-xr-x 1 root     2000 593K Jan  1  2009 sh
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sha1sum -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sha224sum -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sha256sum -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sha384sum -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sha512sum -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sleep -> toybox_vendor
-rwxr-xr-x 1 root     2000 210K Jan  1  2009 slim_daemon
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sort -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 split -> toybox_vendor
-rwxr-xr-x 1 root     2000  11K Jan  1  2009 ssr_diag
-rwxr-xr-x 1 root     2000  11K Jan  1  2009 ssr_setup
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 start -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 stat -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 stop -> toybox_vendor
-rwxr-xr-x 1 root     2000  26K Jan  1  2009 StoreKeybox
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 strings -> toybox_vendor
-rwxr-xr-x 1 root     2000  28K Jan  1  2009 subsystem_ramdump
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 swapoff -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 swapon -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sync -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 sysctl -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 tac -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 tail -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 tar -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 taskset -> toybox_vendor
-rwxr-xr-x 1 root     2000 6.8K Jan  1  2009 tbaseLoader
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 tee -> toybox_vendor
-rwxr-xr-x 1 root     2000  20K Jan  1  2009 test_diag
-rwxr-xr-x 1 root     2000 4.9M Jan  1  2009 thermal-engine
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 time -> toybox_vendor
-rwxr-xr-x 1 root     2000  28K Jan  1  2009 time_daemon
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 timeout -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 top -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 touch -> toybox_vendor
-rwxr-xr-x 1 root     2000 1.3M Jan  1  2009 toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 tr -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 true -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 truncate -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 tty -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 ulimit -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 umount -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 uname -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 uniq -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 unix2dos -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 uptime -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 usleep -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 uudecode -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 uuencode -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 vmstat -> toybox_vendor
-rwxr-xr-x 1 root     2000  36K Jan  1  2009 vndservice
-rwxr-xr-x 1 root     2000 162K Jan  1  2009 vndservicemanager
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 wc -> toybox_vendor
-rwxr-xr-x 1 strcat strcat  68K Jan  1  2009 wcnss_filter
-rwxr-xr-x 1 root     2000  15K Jan  1  2009 wdsdaemon
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 which -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 whoami -> toybox_vendor
-rwxr-xr-x 1 root     2000  24K Jan  1  2009 WifiLogger_app
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 xargs -> toybox_vendor
-rwxr-xr-x 1 root     2000 127K Jan  1  2009 xtra-daemon
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 xxd -> toybox_vendor
lrwxr-xr-x 1 root     2000   13 Jan  1  2009 yes -> toybox_vendor
```

**Comment by anestisb** [comment]
Thanks @thestinger. Since I'm currently away from my build/test infra I have limited testing capabilities. However, I'll try to process within the week the stuff you've submitted and finalise them within the scripts.

**Comment by thestinger** [comment]
@anestisb I don't mind carrying stuff out-of-tree when you aren't doing active development that could conflict with it so don't worry too much. I just wanted to get a head start on this before the Android 8.0 release which will probably around August 21st. I was worried it might be really hard to deal with the Treble related changes, etc. but it doesn't look that bad so far.

**Comment by thestinger** [comment]
I'll be updating this to the stable release today.

**Comment by thestinger** [comment]
The changes in the stable release are very minor. There aren't changes to anything other than the contents of the apks for vendor.img and the list of other stuff that I'm including so far. I'll be comparing to a stock image later to see what's missing.

**Comment by thestinger** [comment]
android-prepare-vendor needs to stop including vendor/etc/NOTICE.xml.gz because it creates a cycle and breaks the build. I'll deal with that later. For now, I edited it out by hand:

```diff
diff --git a/marlin/marlin-vendor-blobs.mk b/marlin/marlin-vendor-blobs.mk
index b72b495..3433a57 100644
--- a/marlin/marlin-vendor-blobs.mk
+++ b/marlin/marlin-vendor-blobs.mk
@@ -197,7 +197,6 @@ PRODUCT_COPY_FILES += \
     vendor/google_devices/marlin/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml:google \
     vendor/google_devices/marlin/vendor/etc/mkshrc:$(TARGET_COPY_OUT_VENDOR)/etc/mkshrc:google \
     vendor/google_devices/marlin/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf:google \
-    vendor/google_devices/marlin/vendor/etc/NOTICE.xml.gz:$(TARGET_COPY_OUT_VENDOR)/etc/NOTICE.xml.gz:google \
     vendor/google_devices/marlin/vendor/etc/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile0.conf:google \
     vendor/google_devices/marlin/vendor/etc/permissions/android.hardware.audio.low_latency.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.audio.low_latency.xml:google \
     vendor/google_devices/marlin/vendor/etc/permissions/android.hardware.audio.pro.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.audio.pro.xml:google \
diff --git a/sailfish/sailfish-vendor-blobs.mk b/sailfish/sailfish-vendor-blobs.mk
index c4b3587..36ff5a5 100644
--- a/sailfish/sailfish-vendor-blobs.mk
+++ b/sailfish/sailfish-vendor-blobs.mk
@@ -197,7 +197,6 @@ PRODUCT_COPY_FILES += \
     vendor/google_devices/sailfish/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml:google \
     vendor/google_devices/sailfish/vendor/etc/mkshrc:$(TARGET_COPY_OUT_VENDOR)/etc/mkshrc:google \
     vendor/google_devices/sailfish/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf:google \
-    vendor/google_devices/sailfish/vendor/etc/NOTICE.xml.gz:$(TARGET_COPY_OUT_VENDOR)/etc/NOTICE.xml.gz:google \
     vendor/google_devices/sailfish/vendor/etc/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile0.conf:google \
     vendor/google_devices/sailfish/vendor/etc/permissions/android.hardware.audio.low_latency.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.audio.low_latency.xml:google \
     vendor/google_devices/sailfish/vendor/etc/permissions/android.hardware.audio.pro.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.audio.pro.xml:google \
```

**Comment by thestinger** [comment]
This now works for the stable release other than needing the API level 26 oatdump workaround for now.

**Pull request merged**
